name: My Workflow
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: PWD
      run: |
        pwd
     - name: ls
      run: |
        ls   
     - name: ls
       run: |
        ls ..
      - name: ls
        run: |
        ls ..
        
    - name: Hello, World!
      uses: ./hello-world-action
